### ISSUE TITLE
Change the shebang :)

### ISSUE THREAD

**Issue by ranomier** [RoryNesbitt/pvim#1]
Instead of writing `#!/bin/sh` write `#!/usr/bin/env sh`.

The latter one checks the `PATH` variable and looks for the binary in those paths :)

Wonderful project!

**Comment by RoryNesbitt** [comment]
Thanks for the note

**Comment by ranomier** [comment]
Just learned that it is possible to use the shebang with lua aswell.

https://artemis.sh/2021/04/25/lua-hashbang-executable-lua-script.html#:~:text=The%20%23!,a%20program%20named%20lua%20exists.

Even with shell at the beginning if you want :)

**Comment by RoryNesbitt** [comment]
That's an interesting read, I was looking at something similar recently for making a file run either in a Linux shell or as windows batch file. The solution was similar but both seem to need the none-shell file extension (.lua or .bat). Something I'm still interested in for making pvim windows compatible

For this project though the lua is executed by Neovim so it's not needed

**Comment by ranomier** [comment]
Oki :)
